name = "blog"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[assets]
directory = "dist"
binding = "ASSETS"

[observability]
enabled = true

[[routes]]
pattern = "www.justaslime.dev"
custom_domain = true

[[kv_namespaces]]
binding = "DRAFTS"
id = "ad24531ef54043d4aab47482370c011d"
